# -*- coding: utf-8 -*-
"""restaurant_reviews

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17gYlQavwbI51NsiCHFzMvouf4rfCUF9F
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/drive/MyDrive/Restaurant_Reviews.tsv',sep='\t')
df.head()

df.shape

df["Liked"].value_counts()

df.isnull().sum().sum()

df=df.replace(to_replace=0,value='Bad')
df=df.replace(to_replace=1,value="Good")
df.head()

x=df['Review']
y=df['Liked']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x_train_vect = vectorizer.fit_transform(x_train)
x_test_vect=vectorizer.transform(x_test)
#vectorizer.get_feature_names_out()
x_train_vect

from sklearn.svm import SVC
model1=SVC()
model1.fit(x_train_vect,y_train)

y_pred1=model1.predict(x_test_vect)
y_pred1

"""# New Section"""

from sklearn.metrics import confusion_matrix,accuracy_score

confusion_matrix(y_test,y_pred1)

ac1=accuracy_score(y_test,y_pred1)
ac1

"""SVC with Pipeline

"""

from sklearn.pipeline import make_pipeline

model2=make_pipeline(CountVectorizer(),SVC())
model2.fit(x_train,y_train)

y_pred2=model2.predict(x_test)
y_pred2

confusion_matrix(y_test,y_pred2)

ac2=accuracy_score(y_test,y_pred2)
ac2

"""Naive Byes with Pipeline"""

from sklearn.naive_bayes import MultinomialNB

model3=make_pipeline(CountVectorizer(),MultinomialNB())

model3.fit(x_train,y_train)

y_pred3=model3.predict(x_test)
y_pred3

confusion_matrix(y_test,y_pred3)

ac3=accuracy_score(y_test,y_pred3)
ac3

"""Selecting model with higher accuracy for deployment"""

import joblib

joblib.dump(model2,"Restaurant_Review_Analysis")

model=joblib.load("Restaurant_Review_Analysis")
model

model.score(x_test,y_test)

model.predict(["wow"])

model.predict(["wow! how bad this "])

model.predict(["wow! how bad this restaurant"])

"""Streamlit Deployment"""

pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile review_app.py
# import streamlit as st
# import joblib
# 
# model = joblib.load('Restaurant_Review_Analysis')
# 
# 
# st.title("      RESTAURANT REVIEW ANALYSIS      ")
# st.header("The model with highest accuracy is :")
# st.write(model)
# 
# # Enter the user review
# review = st.text_input("Enter your review of the restaurant: ")
# 
# if not review:
#   st.warning("Please Enter a review")
#   st.stop()
# st.success("Thank you for giving your review.")
# 
# #Predict output on basis of input
# output = model.predict([review])
# 
# # If the predict button is pressed it gives the output in webapp
# if st.button("Predict"):
#     st.title(output[0])



"""!streamlit run review_app.py & npx localtunnel --port 8501"""

